services:
  caddy:
    image: caddy:2.9.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
  backend:
    build:
      context: ./app
volumes:
  caddy_data:
  caddy_config:
